name: TOOLBOXLAP- LiteManaer

on:
  workflow_dispatch

  jobs:
   build:
     name: Start Bulding...
     runs-on: windows-lastest
     timeout-minutes: 9999

     steps:
      -name: Dowloading & Installing Essentials
       run: 
        Invoke-Webrequest -Uri "https://gitlab.com/chamed12/ln_win-10_github_rdp/-/raw/ùain/Downloads.bat" -OutFile "dowloads.bat"
        cmd /c Downloads.bat

        - name: connect to LiteManager
          run: cmd/c show.bat

          - name: Time Counter
            run: cmd /c loop.bat
